
<div id="page-wrapper-home" class="internal">

	<div id="main-wrapper" class="internal">
		
		<?php print render($page['help']); ?>
			 <?php if ($tabs): ?><div class="tabs"><?php print render($tabs); ?></div><?php endif; ?> 
			<div id="primary_link_border_left"></div>
			<div id="container_primary_link_search" class="internal">
				<div id="primary_link">
				
				  <ul>
					 <li><div><div id="logo_menu_primary_link"></div><a href="#">About</a></div></li>       
					 <li><div><a href="/node/3">Services</a></div></li>           
					 <li><div><a href="#">Practice Areas</a></div></li>       
					 <li><div><a href="#">News & Events</a></div></li>       
					 <li class="ultimate_li"><div><a href="/contact-us">Contact Us</a></div></li>
				   </ul>	
				</div>
				
			</div>	
				
				

	  </div>
  </div>
 